- name: Check if Visual Studio Code is already installed
  command: dpkg-query -W -f='${Status}' code
  register: vscode_installed
  changed_when: false
  failed_when: vscode_installed.stdout.find("install ok installed") == -1
  tags: 'install_vscode'

- name: Get the Visual Studio Code download page
  ansible.builtin.uri:
    url: https://code.visualstudio.com/docs/?dv=linuxarm64_deb
    return_content: yes
  register: download_page
  when: vscode_installed.failed
  tags: 'install_vscode'

- name: Extract the URL of the .deb package
  ansible.builtin.set_fact:
    deb_url: "{{ download_page.content | regex_search('https\\://[^\"\\']*?_arm64\\.deb') }}"
  when: vscode_installed.failed
  tags: 'install_vscode'

- name: Download Visual Studio Code .deb package
  ansible.builtin.get_url:
    url: "{{ deb_url }}"
    dest: "/tmp/{{ deb_url | regex_search('code_[^/]*?_arm64\\.deb') }}"
  when: vscode_installed.failed
  tags: 'install_vscode'

- name: Install Visual Studio Code with dpkg
  ansible.builtin.apt:
    deb: "/tmp/{{ deb_url | regex_search('code_[^/]*?_arm64\\.deb') }}"
  when: vscode_installed.failed
  tags: 'install_vscode'