[33m80b2b3b[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m)[m glutun config actually working
[33m159efe7[m fix first boot
[33m2081e50[m fixes
[33mfd91644[m rm
[33me953ebe[m update, fix pre-installed
[33m6adcfc2[m working image with no wizard
[33mdd1a7e6[m add
[33m3288571[m cleanup
[33m55d2b63[m fix mv issue
[33m138a52f[m trying to modify oem-config
[33m5e2d80b[m shutdown
[33m7af2550[m fix flashing
[33m652324c[m wip
[33m130d3be[m automate actual flashing
[33m63c199d[m flashing
[33m5ded80f[m delete partitions
[33mb4b20f0[m fix OS boot issues due to wireguard
[33me70fbe4[m doc + clean
[33m6335c43[m fix run for remote flash
[33m2e8e321[m fix what is probably bricking the system
[33mf1f6fac[m custom_splash
[33md95493a[m major improvements
[33maa50474[m remote_ansible
[33m8fdb944[m todo
[33ma554c40[m almost wireguard
[33m89a6190[m golang
[33m174dabd[m doc
[33m4f88b58[m Merge pull request #1 from automationStati0n/migration_betterTags
[33m79a5e58[m[33m ([m[1;31morigin/migration_betterTags[m[33m)[m refactor/dynamic
[33m5b338aa[m doc
[33mb307b83[m docker/ansible
[33m67ec106[m correct gluetun command
[33m1c359c1[m var
[33m8234d33[m glueton cmd
[33m08ffb7c[m gluetun
[33m33ec1f6[m dock + rustdesk docker
[33m631708c[m add roles
[33m55c6732[m test
[33mafa822b[m pipewire
[33m0543644[m vino
[33ma9aa3e9[m add
[33mcd50815[m vnc
[33m048b8ff[m vnc,ansible cmd
[33m46a3ae9[m add self ansible
[33maf8bbb6[m doc
[33mce9eb04[m doc
[33m4e9522e[m doc
[33m3af225a[m doc
[33m28cff6e[m doc
[33mb904685[m doc
[33mad6f1b0[m doc
[33m341a614[m doc
[33m0940c8d[m ansible
[33me5e1453[m doc
[33m7829c67[m doc
[33md70924d[m doc
[33m73d0ef7[m todo
[33m7180d40[m doc todo
[33m592d2e0[m doc
[33ma23ca82[m doc
[33m89435f5[m doc
[33m6ae8d6c[m doc
[33m758383a[m doc
[33m38b2d3a[m doc
[33m6c4aa15[m doc
[33mf30d7df[m doc
[33me202437[m doc
[33mb4d1c58[m Update README.md
[33m5f2089c[m Create prompts.md
[33ma59779d[m Update README.md
[33me4aef7d[m Add files via upload
[33m04a21ea[m Delete orangepi5-NVME-Driver-Install.pdf
[33m7625f6d[m Add files via upload
[33mca13259[m Update README.md
[33m11a4377[m Update README.md
[33m8293018[m Initial commit
