#! /bin/bash
# Skipped oem-config on the first boot after shipping to the end user.
set -e

# Immediately proceed with automatic login setup, skipping configuration screens.
# Assuming 'username' is the user you want to automatically log in.

# if sddm.conf exists, add a comment to show that this is the original
# version which existed before end user setup was run 
if [ -f "/etc/sddm.conf" ]; then
        echo "#original_oem_version" >> /etc/sddm.conf
fi

# Remove the oem-config-prepare menu item.
rm -f /usr/share/applications/oem-config-prepare-gtk.desktop \
      /usr/share/applications/kde4/oem-config-prepare-kde.desktop

# Set up automatic login for the user.
if [ -f "/etc/sddm.conf" ]; then
        echo "[Autologin]" >> /etc/sddm.conf
        echo "User=orangepi" >> /etc/sddm.conf
        echo "Session=ubuntu.desktop" >> /etc/sddm.conf
fi

# Enable automatic login for the user.
if [ -f "/etc/gdm3/custom.conf" ]; then
        sed -i '/\[daemon\]/a AutomaticLoginEnable=True' /etc/gdm3/custom.conf
        sed -i "/\[daemon\]/a AutomaticLogin=username" /etc/gdm3/custom.conf
fi

# Enable graphical.target as the default target to boot into GUI.
/bin/systemctl set-default graphical.target || true
/bin/systemctl disable oem-config.service || true
/bin/systemctl disable oem-config.target || true
rm -f /lib/systemd/system/oem-config.* || true

# Ensure the system does not request to reboot.
# /bin/systemctl reboot || true

# Isolate graphical target without blocking.
/bin/systemctl --no-block isolate graphical.target || true

# Remove the script to prevent it from running again.
rm -f /var/lib/oem-config/run

exit 0