- name: Delete all partitions from specified devices
  shell: |
    #!/bin/bash
    for device in /dev/mtdblock0 /dev/nvme0n1; do
      # List partitions and extract the partition numbers
      part_numbers=$(sudo gdisk "$device" << EOF | awk '/^[[:blank:]]*[0-9]+[[:blank:]]+/{print $1}'
    p
    q
    EOF
      )
      
      if [ -n "$part_numbers" ]; then
        # Generate the delete commands for gdisk
        gdisk_cmds="p" # Initialize with print command
        for part_num in $part_numbers; do
          gdisk_cmds="$gdisk_cmds\nd\n$part_num" # Append delete commands
        done
        gdisk_cmds="$gdisk_cmds\nw\nY" # Append write and confirm commands
        
        # Execute the delete commands in gdisk
        echo -e "$gdisk_cmds" | sudo gdisk "$device"
      else
        echo "No partitions found on $device."
      fi
    done    
  args:
    executable: /bin/bash
  register: gdisk_output
  ignore_errors: true

- name: Output result of deletion task
  debug:
    msg:
      - "STDOUT: {{ gdisk_output.stdout_lines }}"
      - "STDERR: {{ gdisk_output.stderr_lines }}"  