- name: Install APT packages
  apt:
    name:
      - ansible
      - firefox
      - flatpak
      - gnome-software-plugin-flatpak
      - kdeconnect
      - git
      - jq
      - wireguard-tools
      # - golang # use ansible role `install_go`
    state: present
    update_cache: yes
  become: true
  tags: package_install  