- name: Install APT packages
  apt:
    name:
      - ansible
      - firefox
      - flatpak
      - gnome-software-plugin-flatpak
      - kdeconnect
      - git
    state: present
    update_cache: yes
  become: true
  tags: package_install  