---
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9117:9117      # Jackett
      - 8080:8080      # qBittorrent WebUI
      - 6881:6881      # qBittorrent TCP
      - 6881:6881/udp  # qBittorrent UDP
      - 11470:11470    # Stremio HTTP
    volumes:
      - /home/orangepi/Github/orangepi5/wg0.conf:/gluetun/wireguard/wg0.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - TZ=
      - UPDATER_PERIOD=

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=30000
      - PGID=30000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - ${QBIT_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=30000
      - PGID=30000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ${QBIT_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - /home/orangepi/Github/orangepi5/docker/qbittorrent/qBittorrent-data.conf:/config/qBittorrent/qBittorrent-data.conf:rw
      - ${DOWNLOADS_PATH}/jackett.json:/config/qBittorrent/nova3/engines/jackett.json:rw
    restart: unless-stopped
    network_mode: "service:gluetun"

  stremio:
    image: stremio/server:latest
    container_name: stremio
    environment:
      - PUID=30000
      - PGID=30000
      - TZ=Etc/UTC
    restart: unless-stopped
    network_mode: "service:gluetun"
