- name: Install required packages for VNC over PipeWire
  ansible.builtin.package:
    name:
      - gnome-remote-desktop
    state: present
  become: true
  tags: start_vnc  

- name: Set VNC authentication method to 'password'
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.remote-desktop.vnc auth-method 'password'
  args:
    creates: "{{ ansible_env.HOME }}/.config/dconf/user"
  become: false
  changed_when: false
  tags: start_vnc  

- name: Set VNC view-only to false
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.remote-desktop.vnc view-only false
  args:
    creates: "{{ ansible_env.HOME }}/.config/dconf/user"
  become: false
  changed_when: false
  tags: start_vnc

- name: Store VNC password in secret-tool
  ansible.builtin.command:
    cmd: "echo -n '{{ vnc_password }}' | secret-tool store --label='GNOME Remote Desktop VNC password' 'xdg:schema' 'org.gnome.RemoteDesktop.VncPassword'"
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/keyrings"
  become: false
  register: secret_tool_output
  changed_when: secret_tool_output.stdout != ""
  no_log: false
  tags: start_vnc  

- name: Get IP address
  ansible.builtin.shell: hostname -I | awk '{print $1}'
  register: ip_address
  changed_when: false
  tags: start_vnc

- name: Enable gnome-remote-desktop service
  ansible.builtin.systemd:
    name: gnome-remote-desktop
    state: started
    enabled: yes
    daemon_reload: yes
    scope: user
  become: false
  notify: Print IP address
  tags: start_vnc
  changed_when: true
# - name: Flush handlers to ensure IP address is printed
#   ansible.builtin.meta: flush_handlers  