- name: Copy the delete_partitions script to the remote machine
  become: true
  copy:
    src: delete_partitions.sh
    dest: /usr/local/bin/delete_partitions.sh
    mode: '0755'

- name: Delete all partitions on specified devices
  become: true
  shell: |
    set -o pipefail
    /usr/local/bin/delete_partitions.sh /dev/mtdblock0 | sudo gdisk /dev/mtdblock0
    /usr/local/bin/delete_partitions.sh /dev/nvme0n1 | sudo gdisk /dev/nvme0n1
  args:
    executable: /bin/bash
  register: gdisk_output
  failed_when: gdisk_output.rc != 0 and ("Cancelled" not in gdisk_output.stderr)