- hosts: localhost
  gather_facts: true
  become: true
  roles:
    - system_update
    - disable_update_notifier
    - package_install
    - flatpak_repo
    - install_rustdesk
    - install_vscode
    - docker
    # - start_vnc # Use rustdesk instead: https://github.com/rustdesk/rustdesk/releases
  # vars: # for - start_vnc 
    # vnc_password: "{{ ansible_become_pass }}" #TODO Remove